[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MacroEnergyScaling = "824dc6dc-8db5-4e55-923f-6cabbd6cfcd5"

[sources]
MacroEnergyScaling = {path = ".."}

[compat]
BenchmarkTools = "1"
JuMP = "1"
julia = "1"
